drop table if exists Person;

create table Person(
	id int GENERATED BY DEFAULT AS IDENTITY,
	name varchar(100) NOT NULL,
	age int CHECK(age >= 0),
	email varchar(50) UNIQUE,
    date_of_birth date,
    mood int,
    created_at timestamp
);

truncate table Person;

insert into Person(name, age, email)
VALUES ('Вадим', 49,'vadim@mail.ru'),
('Елена', 49,'elena@mail.ru'),
('Кирилл', 15,'kirill@mail.ru'),
('Сергей', 34,'sersey@mail.ru');

select * from Person;